name = "phryctoria"
uuid = "4e5f9d5e-d90d-47cf-820d-4dffbf4fca39"
authors = ["Charles Koll <kollch@oregonstate.edu>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Match = "7eb4fadd-790c-5f42-8a69-bfa0b872bfbf"
